[build]
  publish = "."
  command = "echo 'No build required'"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
pk_live_51PXp9pH0SJX1shAzp4uP2WSOIVjNDvkUtc4ONm5f0CctQMBVtwVzDPaK5kr7RJD4uZ84TItPGTBKlAbNYVkiHqEH00yC9aWqab
  OPENAI_API_KEY = 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
