[build]
  publish = "."
  command = "echo 'No build required'"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  STRIPE_PUBLIC_KEY = "your_stripe_public_key_here"
  OPENAI_API_KEY = "your_openai_api_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
